#![allow(clippy::enum_variant_names)]
use std::borrow::Cow;
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use std::sync::LazyLock;

use convert_case::{Case, Casing};
use derive_more::From;
use eserde::Deserialize;
use forge_tool_macros::ToolDescription;
use schemars::{JsonSchema, Schema};
use serde::Serialize;
use serde_json::Map;
use strum::IntoEnumIterator;
use strum_macros::{AsRefStr, Display, EnumDiscriminants, EnumIter};

use crate::{ToolCallArguments, ToolCallFull, ToolDefinition, ToolDescription, ToolName};

/// Enum representing all possible tool input types.
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    JsonSchema,
    From,
    EnumIter,
    Display,
    PartialEq,
    EnumDiscriminants,
)]
#[strum_discriminants(derive(Display, Serialize, Deserialize, Hash))]
#[strum_discriminants(serde(rename_all = "snake_case"))]
#[serde(tag = "name", content = "arguments", rename_all = "snake_case")]
#[strum_discriminants(name(ToolKind))]
#[strum(serialize_all = "snake_case")]
pub enum ToolCatalog {
    #[serde(alias = "Read")]
    Read(FSRead),
    #[serde(alias = "Write")]
    Write(FSWrite),
    FsSearch(FSSearch),
    SemSearch(SemanticSearch),
    Remove(FSRemove),
    Patch(FSPatch),
    MultiPatch(FSMultiPatch),
    Undo(FSUndo),
    Shell(Shell),
    Fetch(NetFetch),
    Followup(Followup),
    Plan(PlanCreate),
    Skill(SkillFetch),
    TodoWrite(TodoWrite),
    TodoRead(TodoRead),
    #[serde(alias = "Task")]
    Task(TaskInput),
}

/// Generic schema for dynamically registered agent tools.
#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
pub struct AgentInput {
    /// Task descriptions for the agent.
    pub tasks: Vec<String>,
}

/// Input structure for the Task tool - delegates work to specialized agents
#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/task.md"]
pub struct TaskInput {
    /// Task descriptions for parallel execution by the agent.
    pub tasks: Vec<String>,

    /// Agent ID (e.g. "forge", "muse", "sage").
    pub agent_id: String,

    /// Optional session ID for continuing existing sessions.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

fn default_true() -> bool {
    true
}

/// Status of a todo item
#[derive(
    Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Display, AsRefStr, EnumIter, Default,
)]
#[serde(rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub enum TodoStatus {
    /// Task is pending and not yet started
    #[default]
    Pending,
    /// Task is currently in progress
    InProgress,
    /// Task has been completed
    Completed,
    /// Task is cancelled and should be removed from the list
    Cancelled,
}

impl JsonSchema for TodoStatus {
    fn schema_name() -> Cow<'static, str> {
        <Self as SimpleEnumSchema>::simple_enum_schema_name()
    }

    fn json_schema(r#gen: &mut schemars::generate::SchemaGenerator) -> Schema {
        <Self as SimpleEnumSchema>::simple_enum_schema(r#gen)
    }
}

/// A todo item
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq, derive_setters::Setters)]
#[setters(strip_option, into)]
pub struct Todo {
    /// Unique identifier for the todo item
    pub id: String,
    /// Content/description of the todo item
    pub content: String,
    /// Current status of the todo
    pub status: TodoStatus,
}

impl Todo {
    /// Creates a new todo with the given content
    pub fn new(content: impl Into<String>) -> Self {
        Self {
            id: String::new(), // Will be generated by service if empty
            content: content.into(),
            status: TodoStatus::default(),
        }
    }

    /// Creates a test fixture todo
    #[cfg(test)]
    pub fn test() -> Self {
        Self {
            id: "test-id".to_string(),
            content: "test content".to_string(),
            status: TodoStatus::default(),
        }
    }

    /// Validates the todo item
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - Content is empty
    /// - Content exceeds maximum length (1000 characters)
    pub fn validate(&self) -> anyhow::Result<()> {
        if self.content.trim().is_empty() {
            anyhow::bail!("Todo content cannot be empty");
        }

        if self.content.len() > 1000 {
            anyhow::bail!("Todo content exceeds maximum length of 1000 characters");
        }

        Ok(())
    }

    /// Checks if the todo is completed
    pub fn is_completed(&self) -> bool {
        self.status == TodoStatus::Completed
    }

    /// Checks if the todo is incomplete (pending or in progress)
    pub fn is_incomplete(&self) -> bool {
        matches!(self.status, TodoStatus::Pending | TodoStatus::InProgress)
    }
}

/// Optional line range for partial file reads.
#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
#[schemars(deny_unknown_fields)]
pub struct FSReadRange {
    /// 1-based first line (inclusive).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_line: Option<i32>,

    /// 1-based last line (inclusive).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_line: Option<i32>,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/fs_read.md"]
#[schemars(deny_unknown_fields)]
pub struct FSRead {
    /// Absolute path to file to read.
    #[serde(alias = "path")]
    pub file_path: String,

    /// Optional line range for partial reads.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub range: Option<FSReadRange>,

    /// Show line numbers. Defaults to true.
    #[serde(default = "default_true")]
    pub show_line_numbers: bool,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/fs_write.md"]
pub struct FSWrite {
    /// Absolute path to file.
    #[serde(alias = "path")]
    pub file_path: String,

    /// Content to write.
    pub content: String,

    /// Overwrite existing files. Error if false and file exists.
    #[serde(default)]
    #[serde(skip_serializing_if = "is_default")]
    pub overwrite: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/fs_search.md"]
#[derive(Default)]
pub struct FSSearch {
    /// Regex pattern to search for.
    pub pattern: String,

    /// File or directory to search in. Defaults to cwd.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,

    /// Glob filter (e.g. "*.js", "*.{ts,tsx}").
    #[serde(skip_serializing_if = "Option::is_none")]
    pub glob: Option<String>,

    /// Output mode: "content" (lines), "files_with_matches" (paths), "count".
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_mode: Option<OutputMode>,

    /// Lines before match (rg -B). Requires output_mode: "content".
    #[serde(rename = "-B", skip_serializing_if = "Option::is_none")]
    pub before_context: Option<u32>,

    /// Lines after match (rg -A). Requires output_mode: "content".
    #[serde(rename = "-A", skip_serializing_if = "Option::is_none")]
    pub after_context: Option<u32>,

    /// Lines before and after match (rg -C). Requires output_mode: "content".
    #[serde(rename = "-C", skip_serializing_if = "Option::is_none")]
    pub context: Option<u32>,

    /// Show line numbers (rg -n). Requires output_mode: "content".
    #[serde(rename = "-n", skip_serializing_if = "Option::is_none")]
    pub show_line_numbers: Option<bool>,

    /// Case insensitive search (rg -i).
    #[serde(rename = "-i", skip_serializing_if = "Option::is_none")]
    pub case_insensitive: Option<bool>,

    /// File type (rg --type). E.g. js, py, rust, go, java.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub file_type: Option<String>,

    /// Limit output to first N entries. Works across all output modes.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub head_limit: Option<u32>,

    /// Skip first N entries before applying head_limit.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offset: Option<u32>,

    /// Multiline mode: . matches newlines (rg -U --multiline-dotall).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub multiline: Option<bool>,
}

/// Output mode for search results
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, AsRefStr, EnumIter)]
#[serde(rename_all = "snake_case")]
pub enum OutputMode {
    /// Show matching lines with content
    Content,
    /// Show only file paths with matches
    FilesWithMatches,
    /// Show match counts per file
    Count,
}

/// A paired query and use_case for semantic search.
#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
pub struct SearchQuery {
    /// Embedding query: WHAT the code does. Use specific technical terms.
    pub query: String,

    /// Reranking query: WHY you need this code. Include keywords (struct/trait/impl/fn).
    pub use_case: String,
}

impl SearchQuery {
    /// Creates a new search query with the given query and use_case
    pub fn new(query: impl Into<String>, use_case: impl Into<String>) -> Self {
        Self { query: query.into(), use_case: use_case.into() }
    }
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/semantic_search.md"]
pub struct SemanticSearch {
    /// 2-3 varied queries recommended for best results.
    pub queries: Vec<SearchQuery>,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/fs_remove.md"]
pub struct FSRemove {
    /// Path of file to remove (absolute).
    pub path: String,
}

/// Operation types that can be performed on matched text
#[derive(Default, Debug, Clone, Serialize, Deserialize, PartialEq, AsRefStr, EnumIter)]
#[serde(rename_all = "snake_case")]
pub enum PatchOperation {
    /// Prepend content before the matched text
    #[default]
    Prepend,

    /// Append content after the matched text
    Append,

    /// Replace first occurrence only.
    Replace,

    /// Replace all occurrences. Use for renaming/refactoring.
    ReplaceAll,

    /// Swap the matched text with another text (search for the second text and
    /// swap them)
    Swap,
}

/// Helper trait to generate simple string enum schemas for unit enums.
///
/// This trait is automatically implemented for enums that derive both
/// `AsRefStr` and `EnumIter`. It provides a consistent way to generate
/// JSON schemas that represent enums as simple string enumerations
/// rather than complex oneOf structures.
trait SimpleEnumSchema: AsRef<str> + IntoEnumIterator {
    fn simple_enum_schema_name() -> Cow<'static, str> {
        std::any::type_name::<Self>()
            .split("::")
            .last()
            .unwrap_or("Enum")
            .to_string()
            .into()
    }

    fn simple_enum_schema(_gen: &mut schemars::generate::SchemaGenerator) -> Schema {
        use schemars::json_schema;
        let variants: Vec<serde_json::Value> = Self::iter()
            .map(|variant| variant.as_ref().to_case(Case::Snake).into())
            .collect();

        json_schema!({
            "type": "string",
            "enum": variants
        })
    }
}

// Blanket implementation for all types that implement AsRef<str> and
// IntoEnumIterator
impl<T> SimpleEnumSchema for T where T: AsRef<str> + IntoEnumIterator {}

impl JsonSchema for PatchOperation {
    fn schema_name() -> Cow<'static, str> {
        <Self as SimpleEnumSchema>::simple_enum_schema_name()
    }

    fn json_schema(r#gen: &mut schemars::generate::SchemaGenerator) -> Schema {
        <Self as SimpleEnumSchema>::simple_enum_schema(r#gen)
    }
}

impl JsonSchema for OutputMode {
    fn schema_name() -> Cow<'static, str> {
        <Self as SimpleEnumSchema>::simple_enum_schema_name()
    }

    fn json_schema(r#gen: &mut schemars::generate::SchemaGenerator) -> Schema {
        <Self as SimpleEnumSchema>::simple_enum_schema(r#gen)
    }
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/fs_patch.md"]
pub struct FSPatch {
    /// Absolute path to file to modify.
    #[serde(alias = "path")]
    pub file_path: String,

    /// Text to replace.
    #[serde(alias = "search")]
    pub old_string: String,

    /// Replace old_string with new_string. Must differ.
    #[serde(alias = "content")]
    pub new_string: String,

    /// Replace all occurrences of old_string (default false)
    /// Replace all occurrences (default false).
    #[serde(default)]
    #[schemars(default)]
    pub replace_all: bool,
}

/// A single edit operation in a multi-patch.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
pub struct PatchEdit {
    /// Text to replace.
    pub old_string: String,

    /// Replace old_string with new_string. Must differ.
    pub new_string: String,

    /// Replace all occurrences (default false).
    #[serde(default)]
    #[schemars(default)]
    pub replace_all: bool,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/fs_multi_patch.md"]
pub struct FSMultiPatch {
    /// Absolute path to file to modify.
    pub file_path: String,

    /// Edit operations applied sequentially.
    pub edits: Vec<PatchEdit>,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/fs_undo.md"]
pub struct FSUndo {
    /// Absolute path of file to revert to prior state.
    pub path: String,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/shell.md"]
pub struct Shell {
    /// Command to execute.
    pub command: String,

    /// Working directory. Defaults to cwd.
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cwd: Option<PathBuf>,

    /// Preserve ANSI codes in output.
    #[serde(default)]
    #[serde(skip_serializing_if = "is_default")]
    pub keep_ansi: bool,

    /// Env var names to pass (e.g. ["PATH", "HOME"]).
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub env: Option<Vec<String>>,

    /// Short description (5-10 words).
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

/// Fetch URL content as markdown or raw text.
#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/net_fetch.md"]
pub struct NetFetch {
    /// URL to fetch.
    pub url: String,

    /// Get raw content without markdown conversion (default: false).
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub raw: Option<bool>,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/followup.md"]
pub struct Followup {
    /// Question to ask.
    pub question: String,

    /// Allow multiple selections (default: single).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub multiple: Option<bool>,

    /// Option 1
    #[serde(skip_serializing_if = "Option::is_none")]
    pub option1: Option<String>,

    /// Option 2
    #[serde(skip_serializing_if = "Option::is_none")]
    pub option2: Option<String>,

    /// Option 3
    #[serde(skip_serializing_if = "Option::is_none")]
    pub option3: Option<String>,

    /// Option 4
    #[serde(skip_serializing_if = "Option::is_none")]
    pub option4: Option<String>,

    /// Option 5
    #[serde(skip_serializing_if = "Option::is_none")]
    pub option5: Option<String>,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/plan_create.md"]
pub struct PlanCreate {
    /// Plan name (used in filename).
    pub plan_name: String,

    /// Version (e.g. "v1", "1.0").
    pub version: String,

    /// Complete plan content in markdown.
    pub content: String,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/skill_fetch.md"]
pub struct SkillFetch {
    /// Skill name (e.g. "pdf", "code_review").
    pub name: String,
}

/// A single todo item. `content` is the unique key for matching.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq)]
pub struct TodoItem {
    /// Task description. Used as unique key to match existing todos.
    pub content: String,
    /// `pending`|`in_progress`|`completed`|`cancelled`
    pub status: crate::TodoStatus,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/todo_write.md"]
pub struct TodoWrite {
    /// Todo items to add/update. `content` is unique key. `cancelled` removes item.
    #[eserde(compat)]
    pub todos: Vec<TodoItem>,
}

#[derive(Default, Debug, Clone, Serialize, Deserialize, JsonSchema, ToolDescription, PartialEq)]
#[tool_description_file = "crates/forge_domain/src/tools/descriptions/todo_read.md"]
pub struct TodoRead {}

fn default_raw() -> Option<bool> {
    Some(false)
}

/// Fetch URL content as markdown or raw text.
#[derive(Default, Deserialize, JsonSchema, ToolDescription, PartialEq)]
pub struct FetchInput {
    /// URL to fetch
    pub url: String,
    /// Get raw content without any markdown conversion (default: false)
    #[serde(default = "default_raw")]
    pub raw: Option<bool>,
}
/// List files/directories at path.
#[derive(Default, Deserialize, JsonSchema, ToolDescription, PartialEq)]
pub struct FSListInput {
    /// The path of the directory to list contents for (absolute path required)
    pub path: String,
    /// Recursive listing (default: top-level only).
    pub recursive: Option<bool>,
}

/// File/dir metadata (size, permissions, timestamps).
#[derive(Default, Deserialize, JsonSchema, ToolDescription, PartialEq)]
pub struct FSFileInfoInput {
    /// Path to file/dir to inspect (absolute).
    pub path: String,
}

#[derive(Deserialize, JsonSchema)]
pub struct UndoInput {
    /// Absolute path of file to revert. Must match prior modification.
    pub path: String,
}

/// Input for the select tool
#[derive(Deserialize, JsonSchema)]
pub struct SelectInput {
    /// Question to ask.
    pub question: String,

    /// First option to choose from
    pub option1: Option<String>,

    /// Second option to choose from
    pub option2: Option<String>,

    /// Third option to choose from
    pub option3: Option<String>,

    /// Fourth option to choose from
    pub option4: Option<String>,

    /// Fifth option to choose from
    pub option5: Option<String>,

    /// Allow multiple selections (default: single).
    #[schemars(default)]
    pub multiple: Option<bool>,
}

/// Helper function to check if a value equals its default value
fn is_default<T: Default + PartialEq>(t: &T) -> bool {
    t == &T::default()
}

impl ToolDescription for ToolCatalog {
    fn description(&self) -> String {
        match self {
            ToolCatalog::Patch(v) => v.description(),
            ToolCatalog::MultiPatch(v) => v.description(),
            ToolCatalog::Shell(v) => v.description(),
            ToolCatalog::Followup(v) => v.description(),
            ToolCatalog::Fetch(v) => v.description(),
            ToolCatalog::FsSearch(v) => v.description(),
            ToolCatalog::SemSearch(v) => v.description(),
            ToolCatalog::Read(v) => v.description(),
            ToolCatalog::Remove(v) => v.description(),
            ToolCatalog::Undo(v) => v.description(),
            ToolCatalog::Write(v) => v.description(),
            ToolCatalog::Plan(v) => v.description(),
            ToolCatalog::Skill(v) => v.description(),
            ToolCatalog::TodoWrite(v) => v.description(),
            ToolCatalog::TodoRead(v) => v.description(),
            ToolCatalog::Task(v) => v.description(),
        }
    }
}
// Cache of all tool names
static FORGE_TOOLS: LazyLock<HashSet<ToolName>> =
    LazyLock::new(|| ToolCatalog::iter().map(ToolName::new).collect());

// Case-insensitive lookup map: lowercase tool name -> canonical tool name
static FORGE_TOOLS_LOWER: LazyLock<HashMap<String, ToolName>> = LazyLock::new(|| {
    ToolCatalog::iter()
        .map(|tool| {
            let name = ToolName::new(tool.to_string());
            (name.as_str().to_lowercase(), name)
        })
        .collect()
});

/// Normalizes a tool name received in a response before catalog matching.
/// Trims surrounding whitespace and performs a case-insensitive lookup
/// against all known catalog tool names, returning the canonical form when
/// a match is found.
fn normalize_tool_name(name: &ToolName) -> ToolName {
    let trimmed = name.as_str().trim();
    let lower = trimmed.to_lowercase();
    FORGE_TOOLS_LOWER
        .get(&lower)
        .cloned()
        .unwrap_or_else(|| ToolName::new(trimmed))
}

impl ToolCatalog {
    pub fn schema(&self) -> Schema {
        use schemars::generate::SchemaSettings;
        use schemars::transform::{AddNullable, Transform};

        let r#gen = SchemaSettings::default()
            .with(|s| {
                s.meta_schema = None;
                s.inline_subschemas = true;
            })
            .into_generator();

        let mut schema = match self {
            ToolCatalog::Patch(_) => r#gen.into_root_schema_for::<FSPatch>(),
            ToolCatalog::MultiPatch(_) => r#gen.into_root_schema_for::<FSMultiPatch>(),
            ToolCatalog::Shell(_) => r#gen.into_root_schema_for::<Shell>(),
            ToolCatalog::Followup(_) => r#gen.into_root_schema_for::<Followup>(),
            ToolCatalog::Fetch(_) => r#gen.into_root_schema_for::<NetFetch>(),
            ToolCatalog::FsSearch(_) => r#gen.into_root_schema_for::<FSSearch>(),
            ToolCatalog::SemSearch(_) => r#gen.into_root_schema_for::<SemanticSearch>(),
            ToolCatalog::Read(_) => r#gen.into_root_schema_for::<FSRead>(),
            ToolCatalog::Remove(_) => r#gen.into_root_schema_for::<FSRemove>(),
            ToolCatalog::Undo(_) => r#gen.into_root_schema_for::<FSUndo>(),
            ToolCatalog::Write(_) => r#gen.into_root_schema_for::<FSWrite>(),
            ToolCatalog::Plan(_) => r#gen.into_root_schema_for::<PlanCreate>(),
            ToolCatalog::Skill(_) => r#gen.into_root_schema_for::<SkillFetch>(),
            ToolCatalog::Task(_) => r#gen.into_root_schema_for::<TaskInput>(),
            ToolCatalog::TodoWrite(_) => r#gen.into_root_schema_for::<TodoWrite>(),
            ToolCatalog::TodoRead(_) => r#gen.into_root_schema_for::<TodoRead>(),
        };

        // Apply transform to add nullable property and remove null from type
        AddNullable::default().transform(&mut schema);

        schema
    }

    pub fn definition(&self) -> ToolDefinition {
        ToolDefinition::new(self)
            .description(self.description())
            .input_schema(self.schema())
    }
    pub fn contains(tool_name: &ToolName) -> bool {
        let normalized = normalize_tool_name(tool_name);
        FORGE_TOOLS.contains(&normalized)
    }
    pub fn should_yield(tool_name: &ToolName) -> bool {
        // Tools that convey that the execution should yield
        let normalized = normalize_tool_name(tool_name);
        [ToolKind::Followup]
            .iter()
            .any(|v| v.to_string().to_case(Case::Snake).eq(normalized.as_str()))
    }

    pub fn requires_stdout(tool_name: &ToolName) -> bool {
        // Tools that require direct stdout/stderr access
        let normalized = normalize_tool_name(tool_name);
        [ToolKind::Shell]
            .iter()
            .any(|v| v.to_string().to_case(Case::Snake).eq(normalized.as_str()))
    }

    /// Convert a tool input to its corresponding domain operation for policy
    /// checking. Returns None for tools that don't require permission
    /// checks.
    pub fn to_policy_operation(
        &self,
        cwd: PathBuf,
    ) -> Option<crate::policies::PermissionOperation> {
        let cwd_path = cwd.clone();
        let display_path_for = |path: &str| {
            format!(
                "`{}`",
                format_display_path(Path::new(path), cwd_path.as_path())
            )
        };

        match self {
            ToolCatalog::Read(input) => Some(crate::policies::PermissionOperation::Read {
                path: std::path::PathBuf::from(&input.file_path),
                cwd,
                message: format!("Read file: {}", display_path_for(&input.file_path)),
            }),
            ToolCatalog::Write(input) => Some(crate::policies::PermissionOperation::Write {
                path: std::path::PathBuf::from(&input.file_path),
                cwd,
                message: format!(
                    "Create/overwrite file: {}",
                    display_path_for(&input.file_path)
                ),
            }),
            ToolCatalog::FsSearch(input) => {
                let path_str = input.path.as_deref().unwrap_or(".");
                let base_message =
                    format!("Search in directory/file: {}", display_path_for(path_str));
                let message = match (&input.glob, &input.file_type) {
                    (Some(glob), _) => {
                        format!(
                            "{base_message} for pattern: '{}' in '{glob}' files",
                            input.pattern
                        )
                    }
                    (None, Some(file_type)) => {
                        format!(
                            "{base_message} for pattern: '{}' in {file_type} files",
                            input.pattern
                        )
                    }
                    (None, None) => {
                        format!("{base_message} for pattern: {}", input.pattern)
                    }
                };
                Some(crate::policies::PermissionOperation::Read {
                    path: std::path::PathBuf::from(path_str),
                    cwd,
                    message,
                })
            }
            ToolCatalog::Remove(input) => Some(crate::policies::PermissionOperation::Write {
                path: std::path::PathBuf::from(&input.path),
                cwd,
                message: format!("Remove file: {}", display_path_for(&input.path)),
            }),
            ToolCatalog::Patch(input) => Some(crate::policies::PermissionOperation::Write {
                path: std::path::PathBuf::from(&input.file_path),
                cwd,
                message: format!("Modify file: {}", display_path_for(&input.file_path)),
            }),
            ToolCatalog::MultiPatch(input) => Some(crate::policies::PermissionOperation::Write {
                path: std::path::PathBuf::from(&input.file_path),
                cwd,
                message: format!(
                    "Modify file with {} edits: {}",
                    input.edits.len(),
                    display_path_for(&input.file_path)
                ),
            }),
            ToolCatalog::Shell(input) => Some(crate::policies::PermissionOperation::Execute {
                command: input.command.clone(),
                cwd,
            }),
            ToolCatalog::Fetch(input) => Some(crate::policies::PermissionOperation::Fetch {
                url: input.url.clone(),
                cwd,
                message: format!("Fetch content from URL: {}", input.url),
            }),
            // Operations that don't require permission checks
            ToolCatalog::SemSearch(_)
            | ToolCatalog::Undo(_)
            | ToolCatalog::Followup(_)
            | ToolCatalog::Plan(_)
            | ToolCatalog::Skill(_)
            | ToolCatalog::TodoWrite(_)
            | ToolCatalog::TodoRead(_)
            | ToolCatalog::Task(_) => None,
        }
    }

    /// Creates a Read tool call with the specified path
    pub fn tool_call_read(path: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Read(FSRead {
            file_path: path.to_string(),
            ..Default::default()
        }))
    }

    /// Creates a Write tool call with the specified path and content
    pub fn tool_call_write(path: &str, content: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Write(FSWrite {
            file_path: path.to_string(),
            content: content.to_string(),
            ..Default::default()
        }))
    }

    /// Creates a Patch tool call with the specified parameters
    pub fn tool_call_patch(
        path: &str,
        content: &str,
        search: &str,
        replace_all: bool,
    ) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Patch(FSPatch {
            file_path: path.to_string(),
            old_string: search.to_string(),
            new_string: content.to_string(),
            replace_all,
        }))
    }

    /// Creates a Remove tool call with the specified path
    pub fn tool_call_remove(path: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Remove(FSRemove { path: path.to_string() }))
    }

    /// Creates a Shell tool call with the specified command and working
    /// directory
    pub fn tool_call_shell(command: &str, cwd: impl Into<PathBuf>) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Shell(Shell {
            command: command.to_string(),
            cwd: Some(cwd.into()),
            ..Default::default()
        }))
    }

    /// Creates a Search tool call with the specified path and pattern
    pub fn tool_call_search(path: &str, pattern: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::FsSearch(FSSearch {
            pattern: pattern.to_string(),
            path: Some(path.to_string()),
            ..Default::default()
        }))
    }

    /// Creates a Semantic Search tool call with the specified queries
    pub fn tool_call_semantic_search(queries: Vec<SearchQuery>) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::SemSearch(SemanticSearch { queries }))
    }

    /// Creates an Undo tool call with the specified path
    pub fn tool_call_undo(path: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Undo(FSUndo { path: path.to_string() }))
    }

    /// Creates a Fetch tool call with the specified url
    pub fn tool_call_fetch(url: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Fetch(NetFetch {
            url: url.to_string(),
            ..Default::default()
        }))
    }

    /// Creates a Followup tool call with the specified question
    pub fn tool_call_followup(question: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Followup(Followup {
            question: question.to_string(),
            ..Default::default()
        }))
    }

    /// Creates a Plan tool call with the specified plan name, version, and
    /// content
    pub fn tool_call_plan(plan_name: &str, version: &str, content: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Plan(PlanCreate {
            plan_name: plan_name.to_string(),
            version: version.to_string(),
            content: content.to_string(),
        }))
    }

    /// Creates a Skill tool call with the specified skill name
    pub fn tool_call_skill(skill_name: &str) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::Skill(SkillFetch {
            name: skill_name.to_string(),
        }))
    }

    /// Creates a TodoWrite tool call with the specified todo items
    pub fn tool_call_todo_write(todos: Vec<crate::TodoItem>) -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::TodoWrite(TodoWrite { todos }))
    }

    /// Creates a TodoRead tool call
    pub fn tool_call_todo_read() -> ToolCallFull {
        ToolCallFull::from(ToolCatalog::TodoRead(TodoRead::default()))
    }

    /// Identifies the kind of the built-in Tools
    pub fn kind(&self) -> ToolKind {
        self.clone().into()
    }
}

fn format_display_path(path: &Path, cwd: &Path) -> String {
    // Try to create a relative path for display if possible
    let display_path = if path.starts_with(cwd) {
        match path.strip_prefix(cwd) {
            Ok(rel_path) => rel_path.display().to_string(),
            Err(_) => path.display().to_string(),
        }
    } else {
        path.display().to_string()
    };

    if display_path.is_empty() {
        ".".to_string()
    } else {
        display_path
    }
}

impl TryFrom<ToolCallFull> for ToolCatalog {
    type Error = crate::Error;

    fn try_from(value: ToolCallFull) -> Result<Self, Self::Error> {
        // Normalize the tool name: trim whitespace and perform case-insensitive
        // catalog match so the serde deserialization receives the canonical name.
        let normalized_name = normalize_tool_name(&value.name);

        let mut map = Map::new();
        map.insert("name".into(), normalized_name.as_str().into());

        // Parse the arguments
        let parsed_args = value.arguments.parse()?;

        // Try to find the tool definition and coerce types based on schema
        let coerced_args = ToolCatalog::iter()
            .find(|tool| tool.definition().name == normalized_name)
            .map(|tool| {
                let schema = tool.definition().input_schema;
                forge_json_repair::coerce_to_schema(parsed_args.clone(), &schema)
            })
            .unwrap_or(parsed_args);

        map.insert("arguments".into(), coerced_args);

        serde_json::from_value(serde_json::Value::Object(map))
            .map_err(|error| crate::Error::AgentCallArgument { error })
    }
}

impl ToolKind {
    pub fn name(&self) -> ToolName {
        ToolName::new(self.to_string().to_case(Case::Snake))
    }

    // TODO: This is an extremely slow operation
    pub fn definition(&self) -> ToolDefinition {
        ToolCatalog::iter()
            .find(|tool| tool.definition().name == self.name())
            .map(|tool| tool.definition())
            .expect("Forge tool definition not found")
    }
}

impl TryFrom<&ToolCallFull> for AgentInput {
    type Error = crate::Error;
    fn try_from(value: &ToolCallFull) -> Result<Self, Self::Error> {
        let value = value.arguments.parse()?;
        serde_json::from_value(value).map_err(|error| crate::Error::AgentCallArgument { error })
    }
}

impl From<ToolCatalog> for ToolCallFull {
    fn from(tool: ToolCatalog) -> Self {
        let name = ToolName::new(tool.to_string());
        // Serialize the tool to get the tagged enum structure
        let value = serde_json::to_value(&tool).expect("Failed to serialize tool");

        // Extract just the "arguments" part from the tagged enum
        let arguments = if let Some(args) = value.get("arguments") {
            ToolCallArguments::from(args.clone())
        } else {
            ToolCallArguments::default()
        };

        ToolCallFull { name, call_id: None, arguments, thought_signature: None }
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use pretty_assertions::assert_eq;
    use strum::IntoEnumIterator;

    use super::Shell;
    use crate::{ToolCatalog, ToolKind, ToolName};

    #[test]
    fn test_tool_definition() {
        let actual = ToolKind::Remove.name();
        let expected = ToolName::new("remove");
        assert_eq!(actual, expected);
    }

    #[test]
    fn test_requires_stdout_for_shell() {
        let fixture = ToolName::new("shell");
        assert!(ToolCatalog::requires_stdout(&fixture));
    }

    #[test]
    fn test_requires_stdout_for_non_shell() {
        let fixture = ToolName::new("read");
        assert!(!ToolCatalog::requires_stdout(&fixture));
    }

    #[test]
    fn test_tool_definition_json() {
        let tools = ToolCatalog::iter()
            .map(|tool| {
                let definition = tool.definition().input_schema;
                serde_json::to_string_pretty(&definition)
                    .expect("Failed to serialize tool definition to JSON")
            })
            .collect::<Vec<_>>()
            .join("\n");

        insta::assert_snapshot!(tools);
    }

    #[test]
    fn test_coerce_string_integers_to_i32() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Simulate the exact error case: read tool with string integers instead of i32
        let tool_call = ToolCallFull {
            name: ToolName::new("read"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"path": "/test/path.rs", "range": {"start_line": 10, "end_line": 20}}"#,
            ),
            thought_signature: None,
        };

        // This should not panic - it should coerce strings to integers
        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse with coerced types"
        );

        if let Ok(ToolCatalog::Read(fs_read)) = actual {
            assert_eq!(fs_read.file_path, "/test/path.rs");
            assert_eq!(fs_read.range.as_ref().and_then(|r| r.start_line), Some(10));
            assert_eq!(fs_read.range.as_ref().and_then(|r| r.end_line), Some(20));
        } else {
            panic!("Expected FSRead variant");
        }
    }

    #[test]
    fn test_coerce_preserves_correct_types() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Verify that already-correct types are preserved
        let tool_call = ToolCallFull {
            name: ToolName::new("read"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"path": "/test/path.rs", "range": {"start_line": 10, "end_line": 20}}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse with correct types"
        );

        if let Ok(ToolCatalog::Read(fs_read)) = actual {
            assert_eq!(fs_read.file_path, "/test/path.rs");
            assert_eq!(fs_read.range.as_ref().and_then(|r| r.start_line), Some(10));
            assert_eq!(fs_read.range.as_ref().and_then(|r| r.end_line), Some(20));
        } else {
            panic!("Expected FSRead variant");
        }
    }

    #[test]
    fn test_capitalized_read_alias() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test that "Read" (capitalized) is normalized to "read"
        let tool_call = ToolCallFull {
            name: ToolName::new("Read"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"path": "/test/path.rs", "range": {"start_line": 10, "end_line": 20}}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse capitalized 'Read' tool name"
        );

        if let Ok(ToolCatalog::Read(fs_read)) = actual {
            assert_eq!(fs_read.file_path, "/test/path.rs");
            assert_eq!(fs_read.range.as_ref().and_then(|r| r.start_line), Some(10));
            assert_eq!(fs_read.range.as_ref().and_then(|r| r.end_line), Some(20));
        } else {
            panic!("Expected FSRead variant");
        }
    }

    #[test]
    fn test_capitalized_write_alias() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test that "Write" (capitalized) is normalized to "write"
        let tool_call = ToolCallFull {
            name: ToolName::new("Write"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"path": "/test/path.rs", "content": "test content"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse capitalized 'Write' tool name"
        );

        if let Ok(ToolCatalog::Write(fs_write)) = actual {
            assert_eq!(fs_write.file_path, "/test/path.rs");
            assert_eq!(fs_write.content, "test content");
        } else {
            panic!("Expected FSWrite variant");
        }
    }

    #[test]
    fn test_lowercase_read_still_works() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Ensure lowercase still works (backward compatibility)
        let tool_call = ToolCallFull {
            name: ToolName::new("read"),
            call_id: None,
            arguments: ToolCallArguments::from_json(r#"{"path": "/test/path.rs"}"#),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse lowercase 'read' tool name"
        );

        matches!(actual.unwrap(), ToolCatalog::Read(_));
    }

    #[test]
    fn test_lowercase_write_still_works() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Ensure lowercase still works (backward compatibility)
        let tool_call = ToolCallFull {
            name: ToolName::new("write"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"path": "/test/path.rs", "content": "test"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse lowercase 'write' tool name"
        );

        matches!(actual.unwrap(), ToolCatalog::Write(_));
    }

    #[test]
    fn test_contains_with_lowercase() {
        assert!(ToolCatalog::contains(&ToolName::new("read")));
        assert!(ToolCatalog::contains(&ToolName::new("write")));
        assert!(!ToolCatalog::contains(&ToolName::new("nonexistent")));
    }

    #[test]
    fn test_contains_with_capitalized() {
        // Test that capitalized versions are also found
        assert!(
            ToolCatalog::contains(&ToolName::new("Read")),
            "Should contain capitalized 'Read'"
        );
        assert!(
            ToolCatalog::contains(&ToolName::new("Write")),
            "Should contain capitalized 'Write'"
        );
    }

    #[test]
    fn test_fs_search_message_with_regex() {
        use std::path::PathBuf;

        use crate::FSSearch;
        use crate::policies::PermissionOperation;

        let search_with_regex = ToolCatalog::FsSearch(FSSearch {
            path: Some("/home/user/project".to_string()),
            pattern: "fn main".to_string(),
            ..Default::default()
        });

        let operation = search_with_regex
            .to_policy_operation(PathBuf::from("/test/cwd"))
            .unwrap();

        match operation {
            PermissionOperation::Read { message, .. } => {
                assert_eq!(
                    message,
                    "Search in directory/file: `/home/user/project` for pattern: fn main"
                );
            }
            _ => panic!("Expected Read operation"),
        }
    }

    #[test]
    fn test_fs_search_message_without_regex() {
        use std::path::PathBuf;

        use crate::FSSearch;
        use crate::policies::PermissionOperation;

        let search_without_regex = ToolCatalog::FsSearch(FSSearch {
            path: Some("/home/user/project".to_string()),
            pattern: ".*".to_string(), // Match all content
            ..Default::default()
        });

        let operation = search_without_regex
            .to_policy_operation(PathBuf::from("/test/cwd"))
            .unwrap();

        match operation {
            PermissionOperation::Read { message, .. } => {
                assert_eq!(
                    message,
                    "Search in directory/file: `/home/user/project` for pattern: .*"
                );
            }
            _ => panic!("Expected Read operation"),
        }
    }

    #[test]
    fn test_fs_search_message_with_file_pattern_only() {
        use std::path::PathBuf;

        use crate::FSSearch;
        use crate::policies::PermissionOperation;

        let search_with_pattern = ToolCatalog::FsSearch(FSSearch {
            path: Some("/home/user/project".to_string()),
            pattern: ".*".to_string(),
            glob: Some("*.rs".to_string()),
            ..Default::default()
        });

        let operation = search_with_pattern
            .to_policy_operation(PathBuf::from("/test/cwd"))
            .unwrap();

        match operation {
            PermissionOperation::Read { message, .. } => {
                assert_eq!(
                    message,
                    "Search in directory/file: `/home/user/project` for pattern: '.*' in '*.rs' files"
                );
            }
            _ => panic!("Expected Read operation"),
        }
    }

    #[test]
    fn test_fs_search_message_with_regex_and_file_pattern() {
        use std::path::PathBuf;

        use crate::FSSearch;
        use crate::policies::PermissionOperation;

        let search_with_both = ToolCatalog::FsSearch(FSSearch {
            path: Some("/home/user/project".to_string()),
            pattern: "fn main".to_string(),
            glob: Some("*.rs".to_string()),
            ..Default::default()
        });

        let operation = search_with_both
            .to_policy_operation(PathBuf::from("/test/cwd"))
            .unwrap();

        match operation {
            PermissionOperation::Read { message, .. } => {
                assert_eq!(
                    message,
                    "Search in directory/file: `/home/user/project` for pattern: 'fn main' in '*.rs' files"
                );
            }
            _ => panic!("Expected Read operation"),
        }
    }

    #[test]
    fn test_fs_patch_backward_compatibility_path() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test old field name "path" still works
        let tool_call = ToolCallFull {
            name: ToolName::new("patch"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"path": "/test/file.rs", "operation": "replace", "new_string": "new", "old_string": "old"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse old 'path' field name"
        );

        if let Ok(ToolCatalog::Patch(fs_patch)) = actual {
            assert_eq!(fs_patch.file_path, "/test/file.rs");
        } else {
            panic!("Expected FSPatch variant");
        }
    }

    #[test]
    fn test_fs_patch_backward_compatibility_search() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test old field name "search" still works
        let tool_call = ToolCallFull {
            name: ToolName::new("patch"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"file_path": "/test/file.rs", "operation": "replace", "new_string": "new", "search": "old text"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse old 'search' field name"
        );

        if let Ok(ToolCatalog::Patch(fs_patch)) = actual {
            assert_eq!(fs_patch.old_string, "old text");
        } else {
            panic!("Expected FSPatch variant");
        }
    }

    #[test]
    fn test_fs_patch_backward_compatibility_content() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test old field name "content" still works
        let tool_call = ToolCallFull {
            name: ToolName::new("patch"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"file_path": "/test/file.rs", "operation": "replace", "content": "new content", "old_string": "old"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse old 'content' field name"
        );

        if let Ok(ToolCatalog::Patch(fs_patch)) = actual {
            assert_eq!(fs_patch.new_string, "new content");
        } else {
            panic!("Expected FSPatch variant");
        }
    }

    #[test]
    fn test_fs_patch_backward_compatibility_all_old_fields() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test all old field names together
        let tool_call = ToolCallFull {
            name: ToolName::new("patch"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"path": "/test/file.rs", "operation": "replace", "content": "new content", "search": "old text"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse all old field names together"
        );

        if let Ok(ToolCatalog::Patch(fs_patch)) = actual {
            assert_eq!(fs_patch.file_path, "/test/file.rs");
            assert_eq!(fs_patch.old_string, "old text");
            assert_eq!(fs_patch.new_string, "new content");
        } else {
            panic!("Expected FSPatch variant");
        }
    }

    #[test]
    fn test_fs_patch_new_field_names() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test new field names work as expected
        let tool_call = ToolCallFull {
            name: ToolName::new("patch"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"file_path": "/test/file.rs", "operation": "replace", "new_string": "new content", "old_string": "old text"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(actual.is_ok(), "Should successfully parse new field names");

        if let Ok(ToolCatalog::Patch(fs_patch)) = actual {
            assert_eq!(fs_patch.file_path, "/test/file.rs");
            assert_eq!(fs_patch.old_string, "old text");
            assert_eq!(fs_patch.new_string, "new content");
        } else {
            panic!("Expected FSPatch variant");
        }
    }

    #[test]
    fn test_fs_patch_with_replace_all() {
        use crate::{ToolCallArguments, ToolCallFull};

        // Test replace_all parameter
        let tool_call = ToolCallFull {
            name: ToolName::new("patch"),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"file_path": "/test/file.rs", "new_string": "new", "old_string": "old", "replace_all": true}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should successfully parse replace_all parameter"
        );

        if let Ok(ToolCatalog::Patch(fs_patch)) = actual {
            assert_eq!(fs_patch.replace_all, true);
        } else {
            panic!("Expected FSPatch variant");
        }
    }

    #[test]
    fn test_unit_enum_schema_generation() {
        use schemars::generate::SchemaSettings;

        use crate::{OutputMode, PatchOperation};

        // Test PatchOperation schema
        let settings = SchemaSettings::default().into_generator();
        let patch_schema = settings.into_root_schema_for::<PatchOperation>();

        // In schemars 1.0, Schema wraps serde_json::Value, so we check the JSON
        // directly
        let schema_value = patch_schema.as_value();
        assert_eq!(schema_value.get("type"), Some(&serde_json::json!("string")));

        let enum_values = schema_value.get("enum").and_then(|v| v.as_array()).unwrap();
        assert_eq!(enum_values.len(), 5);
        assert_eq!(enum_values[0], serde_json::json!("prepend"));
        assert_eq!(enum_values[1], serde_json::json!("append"));

        // Test OutputMode schema
        let settings = SchemaSettings::default().into_generator();
        let output_schema = settings.into_root_schema_for::<OutputMode>();

        // Verify it also generates a simple string enum
        let schema_value = output_schema.as_value();
        assert_eq!(schema_value.get("type"), Some(&serde_json::json!("string")));

        let enum_values = schema_value.get("enum").and_then(|v| v.as_array()).unwrap();
        assert_eq!(enum_values.len(), 3);
        assert_eq!(enum_values[0], serde_json::json!("content"));
        assert_eq!(enum_values[1], serde_json::json!("files_with_matches"));
        assert_eq!(enum_values[2], serde_json::json!("count"));
    }

    #[test]
    fn test_shell_with_description_serialization() {
        use pretty_assertions::assert_eq;

        let fixture = Shell {
            command: "git status".to_string(),
            cwd: Some(PathBuf::from("/test")),
            keep_ansi: false,
            env: None,
            description: Some("Shows working tree status".to_string()),
        };

        let actual = serde_json::to_value(&fixture).unwrap();

        let expected = serde_json::json!({
            "command": "git status",
            "cwd": "/test",
            "description": "Shows working tree status"
        });

        assert_eq!(actual, expected);
    }

    #[test]
    fn test_shell_without_description_serialization() {
        use pretty_assertions::assert_eq;

        let fixture = Shell {
            command: "ls -la".to_string(),
            cwd: Some(PathBuf::from("/home")),
            keep_ansi: false,
            env: None,
            description: None,
        };

        let actual = serde_json::to_value(&fixture).unwrap();

        let expected = serde_json::json!({
            "command": "ls -la",
            "cwd": "/home"
        });

        assert_eq!(actual, expected);
    }

    #[test]
    fn test_shell_without_cwd_serialization() {
        use pretty_assertions::assert_eq;

        let fixture = Shell {
            command: "pwd".to_string(),
            cwd: None,
            keep_ansi: false,
            env: None,
            description: None,
        };

        let actual = serde_json::to_value(&fixture).unwrap();

        let expected = serde_json::json!({
            "command": "pwd"
        });

        assert_eq!(actual, expected);
    }

    #[test]
    fn test_normalize_tool_name_trims_whitespace() {
        let actual = super::normalize_tool_name(&ToolName::new("  read  "));
        let expected = ToolName::new("read");
        assert_eq!(actual, expected);
    }

    #[test]
    fn test_normalize_tool_name_case_insensitive_uppercase() {
        let actual = super::normalize_tool_name(&ToolName::new("READ"));
        let expected = ToolName::new("read");
        assert_eq!(actual, expected);
    }

    #[test]
    fn test_normalize_tool_name_case_insensitive_mixed() {
        let actual = super::normalize_tool_name(&ToolName::new("FS_SEARCH"));
        let expected = ToolName::new("fs_search");
        assert_eq!(actual, expected);
    }

    #[test]
    fn test_normalize_tool_name_trim_and_case_insensitive() {
        let actual = super::normalize_tool_name(&ToolName::new("  SHELL  "));
        let expected = ToolName::new("shell");
        assert_eq!(actual, expected);
    }

    #[test]
    fn test_normalize_tool_name_unknown_returns_trimmed() {
        let actual = super::normalize_tool_name(&ToolName::new("  unknown_tool  "));
        let expected = ToolName::new("unknown_tool");
        assert_eq!(actual, expected);
    }

    #[test]
    fn test_contains_case_insensitive() {
        assert!(ToolCatalog::contains(&ToolName::new("READ")));
        assert!(ToolCatalog::contains(&ToolName::new("Shell")));
        assert!(ToolCatalog::contains(&ToolName::new("PATCH")));
        assert!(!ToolCatalog::contains(&ToolName::new("nonexistent")));
    }

    #[test]
    fn test_contains_with_whitespace() {
        assert!(ToolCatalog::contains(&ToolName::new("  read  ")));
        assert!(ToolCatalog::contains(&ToolName::new(" shell ")));
    }

    #[test]
    fn test_try_from_tool_call_uppercase_name() {
        use crate::{ToolCallArguments, ToolCallFull};

        let tool_call = ToolCallFull {
            name: ToolName::new("SHELL"),
            call_id: None,
            arguments: ToolCallArguments::from_json(r#"{"command": "ls"}"#),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(actual.is_ok(), "Should parse uppercase 'SHELL' tool name");
        assert!(matches!(actual.unwrap(), ToolCatalog::Shell(_)));
    }

    #[test]
    fn test_try_from_tool_call_with_whitespace_name() {
        use crate::{ToolCallArguments, ToolCallFull};

        let tool_call = ToolCallFull {
            name: ToolName::new("  patch  "),
            call_id: None,
            arguments: ToolCallArguments::from_json(
                r#"{"file_path": "/test/file.rs", "new_string": "new", "old_string": "old"}"#,
            ),
            thought_signature: None,
        };

        let actual = ToolCatalog::try_from(tool_call);

        assert!(
            actual.is_ok(),
            "Should parse whitespace-padded 'patch' tool name"
        );
        assert!(matches!(actual.unwrap(), ToolCatalog::Patch(_)));
    }
}
